CREATE DATABASE BOOKMANAGEMENT
GO

USE BOOKMANAGEMENT
GO

CREATE TABLE WRITER(
	ID INT NOT NULL CONSTRAINT PK_WRITER_ID PRIMARY KEY IDENTITY(1,1),
	[NAME] VARCHAR(MAX) NOT NULL,
	IS_ACTIVE BIT NOT NULL CONSTRAINT DF_WRITER_ACTIVE DEFAULT 1
)

CREATE TABLE BOOK (
	ID INT NOT NULL CONSTRAINT PK_BOOK_ID PRIMARY KEY IDENTITY(1,1),
	TITLE VARCHAR(MAX) NOT NULL,
	WRITER_ID INT NOT NULL CONSTRAINT FK_BOOKS_AUTHORS FOREIGN KEY REFERENCES WRITER(ID),
	[YEAR] INT NOT NULL,
	IS_ACTIVE BIT NOT NULL CONSTRAINT DF_BOOK_ACTIVE DEFAULT 1
)
GO